AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31

Globals:
  Function:
    Architectures:
      - arm64
    Handler: app.lambdaHandler
    MemorySize: 128
    Runtime: nodejs22.x
    Timeout: 30

Parameters:
  Env:
    Type: String
    AllowedValues:
      - dev
      - prod
    Default: dev

Resources:
  #########################################
  # Lambda Functions
  #########################################
  ProjectsApiGet:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "${AWS::StackName}-ProjectsApiGet"
      CodeUri: functions/projects-api-get
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /projects
            Method: get
            RestApiId: !Ref ApiGateway
  ProjectsApiGetLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/lambda/${ProjectsApiGet}
      RetentionInDays: 30

  #########################################
  # API Gateway
  #########################################
  ApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      Name: !Sub "${AWS::StackName}-ApiGateway"
      StageName: !Ref Env
      EndpointConfiguration:
        Type: PRIVATE
      OpenApiVersion: "3.0.2"
      DefinitionBody:
        Fn::Transform:
          Name: AWS::Include
          Parameters:
            Location: ./swagger/dist/swagger-backend.yaml
