openapi: "3.0.2"
info:
  title: BFF API
  version: "0.0.1"
servers:
  - url: http://127.0.0.1:3000/api
    description: Development server
paths:
  /projects:
    get:
      summary: Returns a list of projects.
      operationId: getProjects
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  projects:
                    type: array
                    items:
                      $ref: "./schemas.yaml#/Project"
                  tags:
                    type: array
                    items:
                      $ref: "./schemas.yaml#/Tag"
        "4XX":
          description: "Client error"
