openapi: "3.0.2"
info:
  title: API Title
  version: "1.0"
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
servers:
  - url: https://api.server.test/v1
paths:
  /projects:
    get:
      operationId: getProjects
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  list:
                    type: array
                    items:
                      $ref: "./schemas.yaml#/Project"
        "4XX":
          description: "Client error"
  /tags:
    get:
      operationId: getTags
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  list:
                    type: array
                    items:
                      $ref: "./schemas.yaml#/Tag"
        "4XX":
          description: "Client error"
